#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@ustb[-1]
	add ucitrack ustb
	set ucitrack.@ustb[-1].init=ustb
	commit ucitrack
	delete firewall.ustb
	set firewall.ustb=include
	set firewall.ustb.type=script
	set firewall.ustb.path=/usr/share/USTB/rule/firewall.ustb
	set firewall.ustb.reload=1
	commit firewall
EOF

rm -f /tmp/luci-indexcache
exit 0