#!/bin/sh /etc/rc.common
START=50

start() {
	enable=$(uci get ustb.@login[0].enable)
	if [ "$enable" == 1 ]; then
		/usr/share/USTB/link.sh &
	fi
}

stop() {
	pid=$(ps | grep link.sh | grep -v grep | awk '{print $1}')
	if [ "$pid" != "" ]; then
		kill -9 $pid
	fi
	rm -rf /usr/share/USTB/ustb.log
	rm -rf /tmp/ustb.log
}
