#!/bin/sh /etc/rc.common
START=90

start() {
	stop
	enable=$(uci get ustb.@login[0].enable)
	if [ "$enable" == 1 ]; then
		echo "[$(date +'%Y-%m-%d %H:%M:%S')] Service start" >>/usr/share/USTB/link.log
		/usr/share/USTB/script/link.sh &
	fi
}

stop() {
	[ -f /var/run/ustb.pid ] && pid=$(cat /var/run/ustb.pid) || pid=""
	if [ "$pid" != "" ]; then
		kill -9 $pid
		rm -f /var/run/ustb.pid
		echo "[$(date +'%Y-%m-%d %H:%M:%S')] Service stop" >>/usr/share/USTB/link.log
	fi
}
